// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVjDCL0E9nZhzYjuLHntG4zKqcCsLNXLk',
    appId: '1:103870058423:web:7da356d00fe150db212232',
    messagingSenderId: '103870058423',
    projectId: 'tech-smash-61498',
    authDomain: 'tech-smash-61498.firebaseapp.com',
    storageBucket: 'tech-smash-61498.firebasestorage.app',
    measurementId: 'G-2TZ212M7EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvvvWLv98-uOJTGGLWxe4PhKtWx2mA68I',
    appId: '1:103870058423:android:29ce92143733bf10212232',
    messagingSenderId: '103870058423',
    projectId: 'tech-smash-61498',
    storageBucket: 'tech-smash-61498.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOdQ3NEM-oaX1VWXjHras8qiMQD0NXQnM',
    appId: '1:103870058423:ios:a2ef7984113cadca212232',
    messagingSenderId: '103870058423',
    projectId: 'tech-smash-61498',
    storageBucket: 'tech-smash-61498.firebasestorage.app',
    iosBundleId: 'com.example.techSmash',
  );
}
